name: Upload to S3

on:
  push:
    branches:
      - main  # Change this to your main branch or specific branches as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Replace with your AWS region

      - name: Sync files to S3
        run: |
          aws s3 sync /Aashu2139/S3_Cicd_lambda s3://githubactionscicd  --delete --exact-timestamps
